// Builds src/theme.css from a manually-exported scripts/tokens/tokens.json
// (exported via the "SDS - Figma Token JSON" dev plugin, run inside Figma directly —
// used because this Figma plan does not grant the file_variables:read REST API scope).
//
// Run with: node scripts/tokens/build.mjs
import fs from "fs";

const WEIGHT_MAP = { regular: 400, medium: 500, semibold: 600, bold: 700 };

const data = JSON.parse(fs.readFileSync(new URL("./tokens.json", import.meta.url)));
const collections = Object.values(data.collections);

// Index every variable by id, and remember which collection it belongs to.
const byId = {};
for (const collection of collections) {
  for (const [id, variable] of Object.entries(collection.variables)) {
    byId[id] = { ...variable, collectionName: collection.name };
  }
}

function sanitizeSegment(segment) {
  return segment
    .trim()
    .toLowerCase()
    .replace(/%/g, "pct")
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-");
}

function propName(collectionName, name) {
  const segments = name.split("/").map(sanitizeSegment);
  const prefix = collectionName === "Colors" ? ["color"] : [];
  return `--${[...prefix, ...segments].join("-")}`;
}

function pxToRem(px) {
  return `${px / 16}rem`;
}

function rgbToHex({ r, g, b, a }) {
  const toHex = (v) => Math.round(v).toString(16).padStart(2, "0");
  const hex = `#${toHex(r)}${toHex(g)}${toHex(b)}`;
  return a === 1 ? hex : `${hex}${toHex(a * 255)}`;
}

// Resolve a variable's own value (following one level of ALIAS) to a CSS value.
// Colors that alias another variable become var(--that-variables-prop) so the
// primitive -> semantic cascade is preserved instead of being flattened to a hex value.
function resolveCSSValue(variable) {
  const modeValue = Object.values(variable.values)[0];
  if (modeValue.type === "ALIAS") {
    const target = byId[modeValue.value.id];
    return `var(${propName(target.collectionName, target.name)})`;
  }
  if (modeValue.type === "COLOR") {
    return rgbToHex(modeValue.value);
  }
  if (modeValue.type === "STRING") {
    return modeValue.value;
  }
  // NUMBER
  const value = modeValue.value;
  const category = variable.name.split("/")[0];
  if (category === "opacity") return `${value / 100}`;
  if (category === "border" || category === "icon") return `${value}px`;
  if (variable.name === "radius/round") return "9999px";
  return pxToRem(value);
}

const lines = [
  "/*",
  " * This file is automatically generated by scripts/tokens/build.mjs",
  " * Source: scripts/tokens/tokens.json (manual export from the aGenX Figma file)",
  " */",
  ":root {",
];

for (const collection of collections) {
  lines.push(`  /* ${collection.name} */`);
  const entries = Object.values(collection.variables).sort((a, b) =>
    a.name > b.name ? 1 : -1,
  );
  for (const variable of entries) {
    if (
      collection.name === "Typography" &&
      variable.resolvedType === "STRING" &&
      variable.name.startsWith("weight/")
    ) {
      const key = variable.name.split("/")[1];
      lines.push(`  ${propName(collection.name, variable.name)}: ${WEIGHT_MAP[key] ?? 400};`);
      continue;
    }
    if (variable.name.startsWith("font family/")) {
      lines.push(`  ${propName(collection.name, variable.name)}: "${resolveCSSValue(variable)}";`);
      continue;
    }
    lines.push(`  ${propName(collection.name, variable.name)}: ${resolveCSSValue(variable)};`);
  }
}

// Compound text styles -> longhand typography custom properties.
lines.push("  /* Typography styles */");
for (const [name, style] of Object.entries(data.styles.text)) {
  const base = `--typography-${name.split("/").map(sanitizeSegment).join("-")}`;
  const weightKey = style.fontStyle.toLowerCase();
  lines.push(`  ${base}-font-family: "${style.fontFamily}";`);
  lines.push(`  ${base}-font-weight: ${WEIGHT_MAP[weightKey] ?? 400};`);
  lines.push(`  ${base}-font-size: ${pxToRem(style.fontSize)};`);
  lines.push(`  ${base}-line-height: ${pxToRem(style.lineHeight.value)};`);
}

// Effect styles -> box-shadow / backdrop-filter custom properties.
lines.push("  /* Effects */");
for (const [name, style] of Object.entries(data.styles.effect)) {
  const base = `--${name.split("/").map(sanitizeSegment).join("-")}`;
  const shadows = style.effects
    .filter((e) => e.type === "DROP_SHADOW" && e.visible)
    .map((e) => `${e.offset.x}px ${e.offset.y}px ${e.radius}px ${e.spread}px ${rgbToHex(e.color)}`);
  if (shadows.length) lines.push(`  ${base}-shadow: ${shadows.join(", ")};`);
  const blur = style.effects.find((e) => e.type === "BACKGROUND_BLUR" && e.visible);
  if (blur) lines.push(`  ${base}-backdrop-filter: blur(${blur.radius}px);`);
}

lines.push("}");

fs.writeFileSync(new URL("../../src/theme.css", import.meta.url), lines.join("\n") + "\n");
console.log(`Done! Wrote ${Object.keys(byId).length} variables + ${Object.keys(data.styles.text).length} text styles + ${Object.keys(data.styles.effect).length} effect styles to src/theme.css`);
